export const BASE_URL1 = 'https://e-commerce-app-server-theta.vercel.app'
export const BASE_URL2 = 'https://e-commerce-app-server-theta.vercel.app/api/admin'
export const BASE_URL3 = 'https://e-commerce-app-server-theta.vercel.app/api'
export const BASE_URL4 = 'https://e-commerce-app-server-theta.vercel.app/api/cart'
export const BASE_URL5 = 'https://e-commerce-app-server-theta.vercel.app/api'
